name: Build zAuctionHouse
on: [push, pull_request, workflow_dispatch] # workflow_dispatch позволяет запустить сборку кнопкой

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21 # zAuctionHouseV4 требует современную Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        # clean install собирает все модули проекта и упаковывает их правильно
        run: mvn clean install -DskipTests 

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zAuctionHouse-Built
          # Путь к итоговому файлу в папке дистрибуции
          path: target/*.jar
